export const cardStyle = {
  mainCard: {
    width: "594px",
    height: "1049px",
    background: "#FFFFFF",
    borderRadius: "10px",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: "42px",
    position: "relative",
  },
  plusBtn: {
    color: "#fffff",
    padding: "15px",
    width: "40px",
    height: "55px",
  },
  cardAction: {
    position: "absolute",
    width: "593.62px",
    height: "278.86px",
    background: "url(../../assets/images/yellow.png)",
    borderRadius: "10px 10px 0px 0px",
  },
  boxMediate: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "30px",
  },
  dateBase: {
    color: "#ebeced",
    cursor: "pointer",
    width: "20px",
  },
  cardContent: {
    backgroundColor: "#FFFFFF",
    position: "relative",
    padding: "30px",
    height: "530px",
    overflow: "auto",
    paddingTop: 0,
  },
  timeText: {
    fontFamily: "Russo One, sans-serif",
    position: "relative",
    padding: "77px",
    width: "220px",
    height: "30.37px",
    display: "flex",
    fontWeight: "400",
    fontSize: "18px",
    lineHeight: "22px",
    flexDirection: "column",
    alignItems: "flex-end",
    marginLeft: "270px",
    marginTop: "95px",
    color: "#FFFFFF",
  },

  noteBg: {
    backgroundColor: "#ebeced",
    width: "415px",
    height: "20px",
    display: "flex",
    borderRadius: "5px",
    padding: "20px",
    justifyContent: "space-between",
    alignItems: "center",
  },
  calenderIcon: {
    marginLeft: "-45px",
    marginRight: "40px",
    zIndex: 1,
  },
  modalStyle: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 400,
    bgcolor: "background.paper",
    boxShadow: 24,
    p: 4,
  },

  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textField: {
    width: "400px",
    paddingTop: "20px",
  },
  submitBtn: {
    paddingTop: "20px",
    paddingBottom: "20px",
    display: "flex",
    justifyContent: "flex-end",
  },
  emptyContent: {
    display: "flex",
    justifyContent: "space-around",
    padding: "20px",
    // position:'fixed',
    // height:'40px'
  },
  helperText: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 300,
    color: "#ff0000",
    fontSize: "12px",
    lineHeight: 0,
    fontWeight: "bold",
  },
  titlecontent: {
    display: "flex",
    justifyContent: "center",
    color: "#20EEB0",
  },
};
